data_directory: '/scidatalg/reformer-tts/reformer-tts/data/lj-speech-tacotron2'
merged_transcript_csv_path: '/scidatalg/reformer-tts/reformer-tts/data/lj-speech-tacotron2/transcript.csv'
audio_directory: '/scidatalg/reformer-tts/reformer-tts/data/lj-speech-tacotron2/audio'
mel_directory: '/scidatalg/reformer-tts/reformer-tts/data/lj-speech-tacotron2/mel'
dataset:
  use_tacotron2_spectrograms: true
  dict_size: 76
  audio_format:
    max_duration_ms: 768000
    min_duration_ms: 1000
    mono: true
    sampling_rate: 22050
  mel_format:
    hop_length: 256
    n_fft: 1024
    n_mels: 80
    win_length: 1024

experiment:
  experiment_name: "reformer-lj-dropout-clipping-noise-lr-60"
  max_epochs: 1000
  train_workers: 16
  val_workers: 16
  tags: "lj_speech_tacotron2 more_regularization masked_loss double_loss inference_stats tacotron_dropout accumulate_batch clipping_1 half_lr noise bs_60"
  tts_training:
    batch_size: 20
    accumulate_grad_batches: 3
    learning_rate: 0.00005
    gradient_clip_val: 1.
    noise_std: 0.01
    num_visualizations: 10
  save_top_k_checkpoints: 3
  checkpoints_dir: /results/reformer-tts

model:
  dict_size: 76
  num_mel_coeffs: 80
  scp_encoding_dropout: 0.05
  postnet_kwargs:
    dropout: 0.20
  enc_prenet_kwargs:
    dropout: 0.10
  dec_prenet_kwargs:
    dropout: 0.10
