data_directory: '/scidatasm/mo382777/reformer-tts/data/lj-speech-tacotron2'
merged_transcript_csv_path: '/scidatasm/mo382777/reformer-tts/data/lj-speech-tacotron2/transcript.csv'
audio_directory: '/scidatasm/mo382777/reformer-tts/data/lj-speech-tacotron2/audio'
mel_directory: '/scidatasm/mo382777/reformer-tts/data/lj-speech-tacotron2/mel'
dataset:
  use_tacotron2_spectrograms: true
  dict_size: 76
  audio_format:
    max_duration_ms: 768000
    min_duration_ms: 1000
    mono: true
    sampling_rate: 22050
  mel_format:
    hop_length: 256
    n_fft: 1024
    n_mels: 80
    win_length: 1024

experiment:
  experiment_name: "clipping-1_dropout-2x-more"
  max_epochs: 1000
  train_workers: 6
  val_workers: 6
  tags: "lj_speech_tacotron2 more_regularization masked_loss double_loss inference_stats more_dropout clipping_1 k80 accumulate_batch"
  tts_training:
    batch_size: 20
    accumulate_grad_batches: 2
    weight_decay: 0.0001
    gradient_clip_val:  1.
    num_visualizations: 10
  save_top_k_checkpoints: 3
  checkpoints_dir: /results/reformer-tts

model:
  dict_size: 76
  num_mel_coeffs: 80
  scp_encoding_dropout: 0.10
  postnet_kwargs:
    dropout: 0.2
  enc_prenet_kwargs:
    dropout: 0.10
  dec_prenet_kwargs:
    dropout: 0.10
