data_directory: 'data/lj-speech'
merged_transcript_csv_path: 'data/lj-speech/transcript.csv'
audio_directory: 'data/lj-speech/audio'
mel_directory: 'data/lj-speech/mel'
dataset:
  audio_format:
    max_duration_ms: 768000
    min_duration_ms: 1000
    mono: true
    sampling_rate: 22050
  mel_format:
    hop_length: 256
    n_fft: 1024
    n_mels: 80
    win_length: 1024
