data_directory: 'data/lj-speech-tacotron2'
merged_transcript_csv_path: 'data/lj-speech-tacotron2/transcript.csv'
audio_directory: 'data/lj-speech-tacotron2/audio'
mel_directory: 'data/lj-speech-tacotron2/mel'
dataset:
  use_tacotron2_spectrograms: true
  dict_size: 76
  audio_format:
    max_duration_ms: 768000
    min_duration_ms: 1000
    mono: true
    sampling_rate: 22050
  mel_format:
    hop_length: 256
    n_fft: 1024
    n_mels: 80
    win_length: 1024

experiment:
  experiment_name: "reformer-tts_ljtc2"
  max_epochs: 1000
  train_workers: 8
  val_workers: 8
  tags: "lf_speech_tacotron2 first_proper_training"
  tts_training:
    batch_size: 32
    weight_decay: 0.0001
  save_top_k_checkpoints: 5

model:
  dict_size: 76
  num_mel_coeffs: 80
